// ignore_for_file: deprecated_member_use
// ─────────────────────────────────────────────────────────────
//  APP TRANSLATIONS  — All Major Indian Languages (22 total)
// ─────────────────────────────────────────────────────────────

import 'package:flutter/material.dart';

enum AppLanguage {
  english,
  marathi,
  hindi,
  bengali,
  punjabi,
  gujarati,
  telugu,
  kannada,
  tamil,
  malayalam,
  odia,
  assamese,
  urdu,
  konkani,
  maithili,
  santali,
  kashmiri,
  nepali,
  sindhi,
  dogri,
  bodo,
  manipuri,
}

class LanguageInfo {
  final String code;
  final String name;
  final String nativeName;
  final String flag;

  const LanguageInfo({
    required this.code,
    required this.name,
    required this.nativeName,
    required this.flag,
  });
}

class AppTranslations {
  static const Map<AppLanguage, LanguageInfo> languageInfo = {
    AppLanguage.english: LanguageInfo(
      code: 'en',
      name: 'English',
      nativeName: 'English',
      flag: '🇬🇧',
    ),
    AppLanguage.hindi: LanguageInfo(
      code: 'hi',
      name: 'Hindi',
      nativeName: 'हिंदी',
      flag: '🇮🇳',
    ),
    AppLanguage.marathi: LanguageInfo(
      code: 'mr',
      name: 'Marathi',
      nativeName: 'मराठी',
      flag: '🇮🇳',
    ),
    AppLanguage.bengali: LanguageInfo(
      code: 'bn',
      name: 'Bengali',
      nativeName: 'বাংলা',
      flag: '🇮🇳',
    ),
    AppLanguage.telugu: LanguageInfo(
      code: 'te',
      name: 'Telugu',
      nativeName: 'తెలుగు',
      flag: '🇮🇳',
    ),
    AppLanguage.tamil: LanguageInfo(
      code: 'ta',
      name: 'Tamil',
      nativeName: 'தமிழ்',
      flag: '🇮🇳',
    ),
    AppLanguage.gujarati: LanguageInfo(
      code: 'gu',
      name: 'Gujarati',
      nativeName: 'ગુજરાતી',
      flag: '🇮🇳',
    ),
    AppLanguage.kannada: LanguageInfo(
      code: 'kn',
      name: 'Kannada',
      nativeName: 'ಕನ್ನಡ',
      flag: '🇮🇳',
    ),
    AppLanguage.malayalam: LanguageInfo(
      code: 'ml',
      name: 'Malayalam',
      nativeName: 'മലയാളം',
      flag: '🇮🇳',
    ),
    AppLanguage.odia: LanguageInfo(
      code: 'or',
      name: 'Odia',
      nativeName: 'ଓଡ଼ିଆ',
      flag: '🇮🇳',
    ),
    AppLanguage.punjabi: LanguageInfo(
      code: 'pa',
      name: 'Punjabi',
      nativeName: 'ਪੰਜਾਬੀ',
      flag: '🇮🇳',
    ),
    AppLanguage.assamese: LanguageInfo(
      code: 'as',
      name: 'Assamese',
      nativeName: 'অসমীয়া',
      flag: '🇮🇳',
    ),
    AppLanguage.urdu: LanguageInfo(
      code: 'ur',
      name: 'Urdu',
      nativeName: 'اردو',
      flag: '🇮🇳',
    ),
    AppLanguage.konkani: LanguageInfo(
      code: 'kok',
      name: 'Konkani',
      nativeName: 'कोंकणी',
      flag: '🇮🇳',
    ),
    AppLanguage.maithili: LanguageInfo(
      code: 'mai',
      name: 'Maithili',
      nativeName: 'मैथिली',
      flag: '🇮🇳',
    ),
    AppLanguage.santali: LanguageInfo(
      code: 'sat',
      name: 'Santali',
      nativeName: 'ᱥᱟᱱᱛᱟᱲᱤ',
      flag: '🇮🇳',
    ),
    AppLanguage.kashmiri: LanguageInfo(
      code: 'ks',
      name: 'Kashmiri',
      nativeName: 'کٲشُر',
      flag: '🇮🇳',
    ),
    AppLanguage.nepali: LanguageInfo(
      code: 'ne',
      name: 'Nepali',
      nativeName: 'नेपाली',
      flag: '🇮🇳',
    ),
    AppLanguage.sindhi: LanguageInfo(
      code: 'sd',
      name: 'Sindhi',
      nativeName: 'سنڌي',
      flag: '🇮🇳',
    ),
    AppLanguage.dogri: LanguageInfo(
      code: 'doi',
      name: 'Dogri',
      nativeName: 'डोगरी',
      flag: '🇮🇳',
    ),
    AppLanguage.bodo: LanguageInfo(
      code: 'brx',
      name: 'Bodo',
      nativeName: 'बड़ो',
      flag: '🇮🇳',
    ),
    AppLanguage.manipuri: LanguageInfo(
      code: 'mni',
      name: 'Manipuri',
      nativeName: 'মৈতৈলোন্',
      flag: '🇮🇳',
    ),
  };

  static const Map<AppLanguage, Map<String, String>> _strings = {
    // ── ENGLISH ──────────────────────────────────────────────
    AppLanguage.english: {
      'app_name': 'Agri Voice',
      'app_tagline': 'Sustainable Agriculture AI',
      'loading': 'LOADING AI MODEL...',
      'version': 'v2.4.0 • Secure Neural Core',
      'welcome_back': 'Welcome back,',
      'hello_farmer': 'Hello Farmer 🌱',
      'crops_healthy': 'Your crops are looking healthy today.',
      'scan_leaf': 'Scan Leaf',
      'scan_leaf_sub': 'Instant disease detection & advice',
      'local_conditions': 'Local Conditions',
      'temp': 'Temp',
      'sky': 'Sky',
      'humidity': 'Humidity',
      'cloudy': 'Cloudy',
      'tips_today': 'Tips for Today',
      'tips_text':
          'Water plants early morning to prevent fungal growth. Keep an eye on potato leaves for dark spots after last night\'s rain.',
      'common_diseases': 'Common Diseases',
      'tomato': 'Tomato',
      'potato': 'Potato',
      'pepper': 'Pepper',
      'nav_home': 'Home',
      'nav_expert': 'Expert',
      'nav_chat': 'Chat',
      'nav_settings': 'Settings',
      'expert_advisory': 'Expert Advisory',
      'scanned_specimen': 'SCANNED SPECIMEN',
      'disease': 'DISEASE',
      'confidence': 'Confidence',
      'treatment': 'Treatment Recommendation',
      'listen_advisory': 'Listen Advisory',
      'stop_advisory': 'Stop Advisory',
      'speak_advisory': 'Speak Advisory',
      'listening': 'Listening… Tap to finish',
      'speak_hint':
          'Speak in your language — advisory plays back in your language.',
      'scan_another': 'Scan Another Leaf',
      'chat_title': 'Chat with AI Expert',
      'type_message': 'Type a message...',
      'hold_speak': 'TAP MIC TO SPEAK',
      'tap_stop': 'TAP MIC TO STOP',
      'listening_now': 'Listening...',
      'agri_expert': 'Agri Expert',
      'you': 'You',
      'today': 'TODAY',
      'settings': 'Settings',
      'language': 'Language',
      'select_language': 'Select Language',
      'notifications': 'Notifications',
      'about': 'About',
      'version_label': 'Version',
    },

    // ── HINDI ─────────────────────────────────────────────────
    AppLanguage.hindi: {
      'app_name': 'अग्री वॉइस',
      'app_tagline': 'टिकाऊ कृषि AI',
      'loading': 'AI मॉडल लोड हो रहा है...',
      'version': 'v2.4.0 • सुरक्षित न्यूरल कोर',
      'welcome_back': 'वापस स्वागत है,',
      'hello_farmer': 'नमस्ते किसान 🌱',
      'crops_healthy': 'आपकी फसलें आज स्वस्थ दिख रही हैं।',
      'scan_leaf': 'पत्ती स्कैन करें',
      'scan_leaf_sub': 'तत्काल रोग पहचान और सलाह',
      'local_conditions': 'स्थानीय परिस्थितियां',
      'temp': 'तापमान',
      'sky': 'आकाश',
      'humidity': 'नमी',
      'cloudy': 'बादल',
      'tips_today': 'आज के टिप्स',
      'tips_text':
          'फंगल वृद्धि को रोकने के लिए सुबह जल्दी पौधों को पानी दें। पिछली रात की बारिश के बाद आलू की पत्तियों पर काले धब्बों पर नजर रखें।',
      'common_diseases': 'सामान्य रोग',
      'tomato': 'टमाटर',
      'potato': 'आलू',
      'pepper': 'मिर्च',
      'nav_home': 'होम',
      'nav_expert': 'विशेषज्ञ',
      'nav_chat': 'चैट',
      'nav_settings': 'सेटिंग्स',
      'expert_advisory': 'विशेषज्ञ सलाह',
      'scanned_specimen': 'स्कैन किया नमूना',
      'disease': 'रोग',
      'confidence': 'विश्वास',
      'treatment': 'उपचार सुझाव',
      'listen_advisory': 'सलाह सुनें',
      'stop_advisory': 'रोकें',
      'speak_advisory': 'सलाह बोलें',
      'listening': 'सुन रहा है… रोकने के लिए टैप करें',
      'speak_hint': 'अपनी भाषा में बोलें — सलाह आपकी भाषा में सुनाई जाएगी।',
      'scan_another': 'दूसरी पत्ती स्कैन करें',
      'chat_title': 'AI विशेषज्ञ से चैट करें',
      'type_message': 'संदेश टाइप करें...',
      'hold_speak': 'बोलने के लिए माइक टैप करें',
      'tap_stop': 'रोकने के लिए माइक टैप करें',
      'listening_now': 'सुन रहा है...',
      'agri_expert': 'कृषि विशेषज्ञ',
      'you': 'आप',
      'today': 'आज',
      'settings': 'सेटिंग्स',
      'language': 'भाषा',
      'select_language': 'भाषा चुनें',
      'notifications': 'सूचनाएं',
      'about': 'जानकारी',
      'version_label': 'संस्करण',
    },

    // ── MARATHI ───────────────────────────────────────────────
    AppLanguage.marathi: {
      'app_name': 'अॅग्री व्हॉइस',
      'app_tagline': 'शाश्वत कृषी AI',
      'loading': 'AI मॉडेल लोड होत आहे...',
      'version': 'v2.4.0 • सुरक्षित न्यूरल कोर',
      'welcome_back': 'पुन्हा स्वागत आहे,',
      'hello_farmer': 'नमस्कार शेतकरी 🌱',
      'crops_healthy': 'आपली पिके आज निरोगी दिसत आहेत.',
      'scan_leaf': 'पान स्कॅन करा',
      'scan_leaf_sub': 'त्वरित रोग शोध आणि सल्ला',
      'local_conditions': 'स्थानिक परिस्थिती',
      'temp': 'तापमान',
      'sky': 'आकाश',
      'humidity': 'आर्द्रता',
      'cloudy': 'ढगाळ',
      'tips_today': 'आजचे सुझाव',
      'tips_text':
          'बुरशीजन्य वाढ टाळण्यासाठी सकाळी लवकर रोपांना पाणी द्या. रात्रीच्या पावसानंतर बटाट्याच्या पानांवर काळे डाग तपासा.',
      'common_diseases': 'सामान्य रोग',
      'tomato': 'टोमॅटो',
      'potato': 'बटाटा',
      'pepper': 'मिरची',
      'nav_home': 'मुख्यपृष्ठ',
      'nav_expert': 'तज्ञ',
      'nav_chat': 'चॅट',
      'nav_settings': 'सेटिंग्ज',
      'expert_advisory': 'तज्ञ सल्ला',
      'scanned_specimen': 'स्कॅन केलेला नमुना',
      'disease': 'रोग',
      'confidence': 'विश्वासार्हता',
      'treatment': 'उपचार शिफारस',
      'listen_advisory': 'सल्ला ऐका',
      'stop_advisory': 'थांबा',
      'speak_advisory': 'सल्ला बोला',
      'listening': 'ऐकत आहे… थांबण्यासाठी टॅप करा',
      'speak_hint': 'आपल्या भाषेत बोला — सल्ला आपल्या भाषेत ऐकवला जाईल.',
      'scan_another': 'दुसरे पान स्कॅन करा',
      'chat_title': 'AI तज्ञांशी चॅट करा',
      'type_message': 'संदेश टाइप करा...',
      'hold_speak': 'बोलण्यासाठी मायक्रोफोन टॅप करा',
      'tap_stop': 'थांबण्यासाठी मायक्रोफोन टॅप करा',
      'listening_now': 'ऐकत आहे...',
      'agri_expert': 'कृषी तज्ञ',
      'you': 'तुम्ही',
      'today': 'आज',
      'settings': 'सेटिंग्ज',
      'language': 'भाषा',
      'select_language': 'भाषा निवडा',
      'notifications': 'सूचना',
      'about': 'माहिती',
      'version_label': 'आवृत्ती',
    },

    // ── BENGALI ───────────────────────────────────────────────
    AppLanguage.bengali: {
      'app_name': 'অ্যাগ্রি ভয়েস',
      'app_tagline': 'টেকসই কৃষি AI',
      'loading': 'AI মডেল লোড হচ্ছে...',
      'version': 'v2.4.0 • নিরাপদ নিউরাল কোর',
      'welcome_back': 'ফিরে স্বাগতম,',
      'hello_farmer': 'নমস্কার কৃষক 🌱',
      'crops_healthy': 'আপনার ফসল আজ সুস্থ দেখাচ্ছে।',
      'scan_leaf': 'পাতা স্ক্যান করুন',
      'scan_leaf_sub': 'তাৎক্ষণিক রোগ সনাক্তকরণ ও পরামর্শ',
      'local_conditions': 'স্থানীয় অবস্থা',
      'temp': 'তাপমাত্রা',
      'sky': 'আকাশ',
      'humidity': 'আর্দ্রতা',
      'cloudy': 'মেঘলা',
      'tips_today': 'আজকের টিপস',
      'tips_text':
          'ছত্রাক বৃদ্ধি রোধ করতে সকালে গাছে জল দিন। গত রাতের বৃষ্টির পরে আলু পাতায় কালো দাগ দেখুন।',
      'common_diseases': 'সাধারণ রোগ',
      'tomato': 'টমেটো',
      'potato': 'আলু',
      'pepper': 'মরিচ',
      'nav_home': 'হোম',
      'nav_expert': 'বিশেষজ্ঞ',
      'nav_chat': 'চ্যাট',
      'nav_settings': 'সেটিংস',
      'expert_advisory': 'বিশেষজ্ঞ পরামর্শ',
      'scanned_specimen': 'স্ক্যান করা নমুনা',
      'disease': 'রোগ',
      'confidence': 'আস্থা',
      'treatment': 'চিকিৎসা পরামর্শ',
      'listen_advisory': 'পরামর্শ শুনুন',
      'stop_advisory': 'থামুন',
      'speak_advisory': 'পরামর্শ বলুন',
      'listening': 'শুনছি… থামতে ট্যাপ করুন',
      'speak_hint': 'আপনার ভাষায় কথা বলুন।',
      'scan_another': 'অন্য পাতা স্ক্যান করুন',
      'chat_title': 'AI বিশেষজ্ঞের সাথে চ্যাট করুন',
      'type_message': 'বার্তা টাইপ করুন...',
      'hold_speak': 'কথা বলতে মাইক ট্যাপ করুন',
      'tap_stop': 'থামতে মাইক ট্যাপ করুন',
      'listening_now': 'শুনছি...',
      'agri_expert': 'কৃষি বিশেষজ্ঞ',
      'you': 'আপনি',
      'today': 'আজ',
      'settings': 'সেটিংস',
      'language': 'ভাষা',
      'select_language': 'ভাষা নির্বাচন করুন',
      'notifications': 'বিজ্ঞপ্তি',
      'about': 'সম্পর্কে',
      'version_label': 'সংস্করণ',
    },

    // ── TELUGU ────────────────────────────────────────────────
    AppLanguage.telugu: {
      'app_name': 'అగ్రి వాయిస్',
      'app_tagline': 'స్థిరమైన వ్యవసాయ AI',
      'loading': 'AI మోడల్ లోడ్ అవుతోంది...',
      'version': 'v2.4.0 • సురక్షిత న్యూరల్ కోర్',
      'welcome_back': 'తిరిగి స్వాగతం,',
      'hello_farmer': 'నమస్కారం రైతు 🌱',
      'crops_healthy': 'మీ పంటలు ఈరోజు ఆరోగ్యంగా ఉన్నాయి.',
      'scan_leaf': 'ఆకు స్కాన్ చేయండి',
      'scan_leaf_sub': 'తక్షణ వ్యాధి గుర్తింపు మరియు సలహా',
      'local_conditions': 'స్థానిక పరిస్థితులు',
      'temp': 'ఉష్ణోగ్రత',
      'sky': 'ఆకాశం',
      'humidity': 'తేమ',
      'cloudy': 'మేఘావృతం',
      'tips_today': 'నేటి చిట్కాలు',
      'tips_text':
          'శిలీంధ్ర వృద్ధిని నివారించడానికి తెల్లవారుజామున మొక్కలకు నీరు పోయండి.',
      'common_diseases': 'సాధారణ వ్యాధులు',
      'tomato': 'టమాటా',
      'potato': 'బంగాళాదుంప',
      'pepper': 'మిరప',
      'nav_home': 'హోమ్',
      'nav_expert': 'నిపుణుడు',
      'nav_chat': 'చాట్',
      'nav_settings': 'సెట్టింగ్‌లు',
      'expert_advisory': 'నిపుణుల సలహా',
      'scanned_specimen': 'స్కాన్ చేసిన నమూనా',
      'disease': 'వ్యాధి',
      'confidence': 'విశ్వాసం',
      'treatment': 'చికిత్స సిఫారసు',
      'listen_advisory': 'సలహా వినండి',
      'stop_advisory': 'ఆపండి',
      'speak_advisory': 'సలహా మాట్లాడండి',
      'listening': 'వింటున్నాను…',
      'speak_hint': 'మీ భాషలో మాట్లాడండి.',
      'scan_another': 'మరో ఆకు స్కాన్ చేయండి',
      'chat_title': 'AI నిపుణుడితో చాట్ చేయండి',
      'type_message': 'సందేశం టైప్ చేయండి...',
      'hold_speak': 'మాట్లాడడానికి మైక్ నొక్కండి',
      'tap_stop': 'ఆపడానికి మైక్ నొక్కండి',
      'listening_now': 'వింటున్నాను...',
      'agri_expert': 'వ్యవసాయ నిపుణుడు',
      'you': 'మీరు',
      'today': 'నేడు',
      'settings': 'సెట్టింగ్‌లు',
      'language': 'భాష',
      'select_language': 'భాష ఎంచుకోండి',
      'notifications': 'నోటిఫికేషన్‌లు',
      'about': 'గురించి',
      'version_label': 'వెర్షన్',
    },

    // ── TAMIL ─────────────────────────────────────────────────
    AppLanguage.tamil: {
      'app_name': 'அக்ரி வாய்ஸ்',
      'app_tagline': 'நிலையான வேளாண்மை AI',
      'loading': 'AI மாதிரி ஏற்றப்படுகிறது...',
      'version': 'v2.4.0 • பாதுகாப்பான நரம்பியல் மையம்',
      'welcome_back': 'மீண்டும் வருக,',
      'hello_farmer': 'வணக்கம் விவசாயி 🌱',
      'crops_healthy': 'உங்கள் பயிர்கள் இன்று ஆரோக்கியமாக உள்ளன.',
      'scan_leaf': 'இலையை ஸ்கேன் செய்யுங்கள்',
      'scan_leaf_sub': 'உடனடி நோய் கண்டறிதல் & ஆலோசனை',
      'local_conditions': 'உள்ளூர் நிலைமைகள்',
      'temp': 'வெப்பநிலை',
      'sky': 'வானம்',
      'humidity': 'ஈரப்பதம்',
      'cloudy': 'மேகமூட்டம்',
      'tips_today': 'இன்றைய குறிப்புகள்',
      'tips_text':
          'பூஞ்சை வளர்ச்சியை தடுக்க காலையில் சீக்கிரம் தாவரங்களுக்கு தண்ணீர் பாயுங்கள்.',
      'common_diseases': 'பொதுவான நோய்கள்',
      'tomato': 'தக்காளி',
      'potato': 'உருளைக்கிழங்கு',
      'pepper': 'மிளகாய்',
      'nav_home': 'முகப்பு',
      'nav_expert': 'நிபுணர்',
      'nav_chat': 'அரட்டை',
      'nav_settings': 'அமைப்புகள்',
      'expert_advisory': 'நிபுணர் ஆலோசனை',
      'scanned_specimen': 'ஸ்கேன் செய்த மாதிரி',
      'disease': 'நோய்',
      'confidence': 'நம்பகத்தன்மை',
      'treatment': 'சிகிச்சை பரிந்துரை',
      'listen_advisory': 'ஆலோசனை கேளுங்கள்',
      'stop_advisory': 'நிறுத்துங்கள்',
      'speak_advisory': 'ஆலோசனை பேசுங்கள்',
      'listening': 'கேட்கிறேன்…',
      'speak_hint': 'உங்கள் மொழியில் பேசுங்கள்.',
      'scan_another': 'மற்றொரு இலையை ஸ்கேன் செய்யுங்கள்',
      'chat_title': 'AI நிபுணருடன் அரட்டையடிக்கவும்',
      'type_message': 'செய்தி தட்டச்சு செய்யுங்கள்...',
      'hold_speak': 'பேச மைக்கை தட்டவும்',
      'tap_stop': 'நிறுத்த மைக்கை தட்டவும்',
      'listening_now': 'கேட்கிறேன்...',
      'agri_expert': 'வேளாண் நிபுணர்',
      'you': 'நீங்கள்',
      'today': 'இன்று',
      'settings': 'அமைப்புகள்',
      'language': 'மொழி',
      'select_language': 'மொழியை தேர்ந்தெடுக்கவும்',
      'notifications': 'அறிவிப்புகள்',
      'about': 'பற்றி',
      'version_label': 'பதிப்பு',
    },

    // ── GUJARATI ──────────────────────────────────────────────
    AppLanguage.gujarati: {
      'app_name': 'અૅગ્રી વૉઇસ',
      'app_tagline': 'ટકાઉ કૃષિ AI',
      'loading': 'AI મોડેલ લોડ થઈ રહ્યું છે...',
      'version': 'v2.4.0 • સુરક્ષિત ન્યૂરલ કોર',
      'welcome_back': 'પાછા સ્વાગત છે,',
      'hello_farmer': 'નમસ્તે ખેડૂત 🌱',
      'crops_healthy': 'તમારા પાક આજે સ્વસ્થ દેખાય છે.',
      'scan_leaf': 'પાન સ્કૅન કરો',
      'scan_leaf_sub': 'તત્કાળ રોગ શોધ અને સલાહ',
      'local_conditions': 'સ્થાનિક પરિસ્થિતિ',
      'temp': 'તાપમાન',
      'sky': 'આકાશ',
      'humidity': 'ભેજ',
      'cloudy': 'વાદળછાયું',
      'tips_today': 'આજની ટિપ્સ',
      'tips_text': 'ફૂગ વૃદ્ધિ અટકાવવા સવારે વહેલા છોડને પાણી આપો.',
      'common_diseases': 'સામાન્ય રોગ',
      'tomato': 'ટામેટું',
      'potato': 'બટાકા',
      'pepper': 'મરચું',
      'nav_home': 'હોમ',
      'nav_expert': 'નિષ્ણાત',
      'nav_chat': 'ચેટ',
      'nav_settings': 'સેટિંગ્સ',
      'expert_advisory': 'નિષ્ણાત સલાહ',
      'scanned_specimen': 'સ્કૅન કરેલ નમૂનો',
      'disease': 'રોગ',
      'confidence': 'વિશ્વાસ',
      'treatment': 'સારવાર ભલામણ',
      'listen_advisory': 'સલાહ સાંભળો',
      'stop_advisory': 'અટકો',
      'speak_advisory': 'સલાહ બોલો',
      'listening': 'સાંભળી રહ્યો છું…',
      'speak_hint': 'તમારી ભાષામાં બોલો.',
      'scan_another': 'બીજું પાન સ્કૅન કરો',
      'chat_title': 'AI નિષ્ણાત સાથે ચેટ કરો',
      'type_message': 'સંદેશ ટાઇપ કરો...',
      'hold_speak': 'બોલવા માટે માઇક ટૅપ કરો',
      'tap_stop': 'અટકવા માટે માઇક ટૅપ કરો',
      'listening_now': 'સાંભળી રહ્યો છું...',
      'agri_expert': 'કૃષિ નિષ્ણાત',
      'you': 'તમે',
      'today': 'આજ',
      'settings': 'સેટિંગ્સ',
      'language': 'ભાષા',
      'select_language': 'ભાષા પસંદ કરો',
      'notifications': 'સૂચનાઓ',
      'about': 'માહિતી',
      'version_label': 'આવૃત્તિ',
    },

    // ── KANNADA ───────────────────────────────────────────────
    AppLanguage.kannada: {
      'app_name': 'ಅಗ್ರಿ ವಾಯ್ಸ್',
      'app_tagline': 'ಸಮರ್ಥನೀಯ ಕೃಷಿ AI',
      'loading': 'AI ಮಾದರಿ ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
      'version': 'v2.4.0 • ಸುರಕ್ಷಿತ ನ್ಯೂರಲ್ ಕೋರ್',
      'welcome_back': 'ಮತ್ತೆ ಸ್ವಾಗತ,',
      'hello_farmer': 'ನಮಸ್ಕಾರ ರೈತ 🌱',
      'crops_healthy': 'ನಿಮ್ಮ ಬೆಳೆಗಳು ಇಂದು ಆರೋಗ್ಯಕರವಾಗಿ ಕಾಣುತ್ತಿವೆ.',
      'scan_leaf': 'ಎಲೆ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
      'scan_leaf_sub': 'ತಕ್ಷಣ ರೋಗ ಪತ್ತೆ ಮತ್ತು ಸಲಹೆ',
      'local_conditions': 'ಸ್ಥಳೀಯ ಪರಿಸ್ಥಿತಿಗಳು',
      'temp': 'ತಾಪಮಾನ',
      'sky': 'ಆಕಾಶ',
      'humidity': 'ತೇವಾಂಶ',
      'cloudy': 'ಮೋಡ ಕವಿದ',
      'tips_today': 'ಇಂದಿನ ಸಲಹೆಗಳು',
      'tips_text': 'ಶಿಲೀಂಧ್ರ ಬೆಳವಣಿಗೆ ತಡೆಯಲು ಬೆಳಿಗ್ಗೆ ಬೇಗ ಗಿಡಗಳಿಗೆ ನೀರು ಹಾಕಿ.',
      'common_diseases': 'ಸಾಮಾನ್ಯ ರೋಗಗಳು',
      'tomato': 'ಟೊಮೇಟೊ',
      'potato': 'ಆಲೂಗಡ್ಡೆ',
      'pepper': 'ಮೆಣಸಿನಕಾಯಿ',
      'nav_home': 'ಮನೆ',
      'nav_expert': 'ತಜ್ಞ',
      'nav_chat': 'ಚಾಟ್',
      'nav_settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      'expert_advisory': 'ತಜ್ಞ ಸಲಹೆ',
      'scanned_specimen': 'ಸ್ಕ್ಯಾನ್ ಮಾಡಿದ ಮಾದರಿ',
      'disease': 'ರೋಗ',
      'confidence': 'ವಿಶ್ವಾಸ',
      'treatment': 'ಚಿಕಿತ್ಸೆ ಶಿಫಾರಸು',
      'listen_advisory': 'ಸಲಹೆ ಕೇಳಿ',
      'stop_advisory': 'ನಿಲ್ಲಿಸಿ',
      'speak_advisory': 'ಸಲಹೆ ಮಾತನಾಡಿ',
      'listening': 'ಕೇಳುತ್ತಿದ್ದೇನೆ…',
      'speak_hint': 'ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಮಾತನಾಡಿ.',
      'scan_another': 'ಇನ್ನೊಂದು ಎಲೆ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
      'chat_title': 'AI ತಜ್ಞರೊಂದಿಗೆ ಚಾಟ್ ಮಾಡಿ',
      'type_message': 'ಸಂದೇಶ ಟೈಪ್ ಮಾಡಿ...',
      'hold_speak': 'ಮಾತನಾಡಲು ಮೈಕ್ ಟ್ಯಾಪ್ ಮಾಡಿ',
      'tap_stop': 'ನಿಲ್ಲಿಸಲು ಮೈಕ್ ಟ್ಯಾಪ್ ಮಾಡಿ',
      'listening_now': 'ಕೇಳುತ್ತಿದ್ದೇನೆ...',
      'agri_expert': 'ಕೃಷಿ ತಜ್ಞ',
      'you': 'ನೀವು',
      'today': 'ಇಂದು',
      'settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      'language': 'ಭಾಷೆ',
      'select_language': 'ಭಾಷೆ ಆಯ್ಕೆ ಮಾಡಿ',
      'notifications': 'ಅಧಿಸೂಚನೆಗಳು',
      'about': 'ಬಗ್ಗೆ',
      'version_label': 'ಆವೃತ್ತಿ',
    },

    // ── MALAYALAM ─────────────────────────────────────────────
    AppLanguage.malayalam: {
      'app_name': 'അഗ്രി വോയ്സ്',
      'app_tagline': 'സുസ്ഥിര കൃഷി AI',
      'loading': 'AI മോഡൽ ലോഡ് ചെയ്യുന്നു...',
      'version': 'v2.4.0 • സുരക്ഷിത ന്യൂറൽ കോർ',
      'welcome_back': 'തിരിച്ചു സ്വാഗതം,',
      'hello_farmer': 'നമസ്കാരം കർഷകൻ 🌱',
      'crops_healthy': 'നിങ്ങളുടെ വിളകൾ ഇന്ന് ആരോഗ്യകരമായി കാണുന്നു.',
      'scan_leaf': 'ഇല സ്കാൻ ചെയ്യുക',
      'scan_leaf_sub': 'തൽക്ഷണ രോഗ കണ്ടെത്തൽ & ഉപദേശം',
      'local_conditions': 'പ്രാദേശിക അവസ്ഥകൾ',
      'temp': 'താപനില',
      'sky': 'ആകാശം',
      'humidity': 'ഈർപ്പം',
      'cloudy': 'മേഘാവൃതം',
      'tips_today': 'ഇന്നത്തെ നുറുങ്ങുകൾ',
      'tips_text': 'ഫംഗൽ വളർച്ച തടയാൻ രാവിലെ നേരത്തെ ചെടികൾക്ക് വെള്ളം നൽകുക.',
      'common_diseases': 'സാധാരണ രോഗങ്ങൾ',
      'tomato': 'തക്കാളി',
      'potato': 'ഉരുളക്കിഴങ്ങ്',
      'pepper': 'മുളക്',
      'nav_home': 'ഹോം',
      'nav_expert': 'വിദഗ്ധൻ',
      'nav_chat': 'ചാറ്റ്',
      'nav_settings': 'ക്രമീകരണങ്ങൾ',
      'expert_advisory': 'വിദഗ്ധ ഉപദേശം',
      'scanned_specimen': 'സ്കാൻ ചെയ്ത സാമ്പിൾ',
      'disease': 'രോഗം',
      'confidence': 'വിശ്വാസ്യത',
      'treatment': 'ചികിത്സ ശുപാർശ',
      'listen_advisory': 'ഉപദേശം കേൾക്കുക',
      'stop_advisory': 'നിർത്തുക',
      'speak_advisory': 'ഉപദേശം പറയുക',
      'listening': 'കേൾക്കുന്നു…',
      'speak_hint': 'നിങ്ങളുടെ ഭാഷയിൽ സംസാരിക്കുക.',
      'scan_another': 'മറ്റൊരു ഇല സ്കാൻ ചെയ്യുക',
      'chat_title': 'AI വിദഗ്ധനുമായി ചാറ്റ് ചെയ്യുക',
      'type_message': 'സന്ദേശം ടൈപ്പ് ചെയ്യുക...',
      'hold_speak': 'സംസാരിക്കാൻ മൈക്ക് ടാപ്പ് ചെയ്യുക',
      'tap_stop': 'നിർത്താൻ മൈക്ക് ടാപ്പ് ചെയ്യുക',
      'listening_now': 'കേൾക്കുന്നു...',
      'agri_expert': 'കൃഷി വിദഗ്ധൻ',
      'you': 'നിങ്ങൾ',
      'today': 'ഇന്ന്',
      'settings': 'ക്രമീകരണങ്ങൾ',
      'language': 'ഭാഷ',
      'select_language': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
      'notifications': 'അറിയിപ്പുകൾ',
      'about': 'കുറിച്ച്',
      'version_label': 'പതിപ്പ്',
    },

    // ── ODIA ──────────────────────────────────────────────────
    AppLanguage.odia: {
      'app_name': 'ଅଗ୍ରି ଭଏସ୍',
      'app_tagline': 'ଟିକସଯୋଗ୍ୟ କୃଷି AI',
      'loading': 'AI ମଡେଲ ଲୋଡ ହେଉଛି...',
      'version': 'v2.4.0 • ସୁରକ୍ଷିତ ନ୍ୟୁରାଲ କୋର',
      'welcome_back': 'ଫେରି ସ୍ୱାଗତ,',
      'hello_farmer': 'ନମସ୍କାର କୃଷକ 🌱',
      'crops_healthy': 'ଆପଣଙ୍କ ଫସଲ ଆଜି ସୁସ୍ଥ ଦେଖାଯାଉଛି।',
      'scan_leaf': 'ପତ୍ର ସ୍କାନ କରନ୍ତୁ',
      'scan_leaf_sub': 'ତୁରନ୍ତ ରୋଗ ଚିହ୍ନଟ ଏବଂ ପରାମର୍ଶ',
      'local_conditions': 'ସ୍ଥାନୀୟ ଅବସ୍ଥା',
      'temp': 'ତାପମାତ୍ରା',
      'sky': 'ଆକାଶ',
      'humidity': 'ଆର୍ଦ୍ରତା',
      'cloudy': 'ମେଘଳା',
      'tips_today': 'ଆଜିର ଟିପ୍ସ',
      'tips_text': 'ଫଙ୍ଗଲ ବୃଦ୍ଧି ରୋକିବାକୁ ସକାଳୁ ଗଛମାନଙ୍କୁ ପାଣି ଦିଅନ୍ତୁ।',
      'common_diseases': 'ସାଧାରଣ ରୋଗ',
      'tomato': 'ଟମାଟୋ',
      'potato': 'ଆଳୁ',
      'pepper': 'ଲଙ୍କା',
      'nav_home': 'ହୋମ',
      'nav_expert': 'ବିଶେଷଜ୍ଞ',
      'nav_chat': 'ଚାଟ',
      'nav_settings': 'ସେଟିଂସ',
      'expert_advisory': 'ବିଶେଷଜ୍ଞ ପରାମର୍ଶ',
      'scanned_specimen': 'ସ୍କାନ ହୋଇଥିବା ନମୁନା',
      'disease': 'ରୋଗ',
      'confidence': 'ବିଶ୍ୱାସ',
      'treatment': 'ଚିକିତ୍ସା ସୁପାରିଶ',
      'listen_advisory': 'ପରାମର୍ଶ ଶୁଣନ୍ତୁ',
      'stop_advisory': 'ବନ୍ଦ କରନ୍ତୁ',
      'speak_advisory': 'ପରାମର୍ଶ ବୋଲନ୍ତୁ',
      'listening': 'ଶୁଣୁଛି…',
      'speak_hint': 'ଆପଣଙ୍କ ଭାଷାରେ କୁହନ୍ତୁ।',
      'scan_another': 'ଅନ୍ୟ ପତ୍ର ସ୍କାନ କରନ୍ତୁ',
      'chat_title': 'AI ବିଶେଷଜ୍ଞଙ୍କ ସହ ଚାଟ କରନ୍ତୁ',
      'type_message': 'ବାର୍ତ୍ତା ଟାଇପ କରନ୍ତୁ...',
      'hold_speak': 'କହିବାକୁ ମାଇକ ଟ୍ୟାପ କରନ୍ତୁ',
      'tap_stop': 'ବନ୍ଦ କରିବାକୁ ମାଇକ ଟ୍ୟାପ କରନ୍ତୁ',
      'listening_now': 'ଶୁଣୁଛି...',
      'agri_expert': 'କୃଷି ବିଶେଷଜ୍ଞ',
      'you': 'ଆପଣ',
      'today': 'ଆଜି',
      'settings': 'ସେଟିଂସ',
      'language': 'ଭାଷା',
      'select_language': 'ଭାଷା ବାଛନ୍ତୁ',
      'notifications': 'ବିଜ୍ଞପ୍ତି',
      'about': 'ବିଷୟରେ',
      'version_label': 'ସଂସ୍କରଣ',
    },

    // ── PUNJABI ───────────────────────────────────────────────
    AppLanguage.punjabi: {
      'app_name': 'ਅਗਰੀ ਵਾਇਸ',
      'app_tagline': 'ਟਿਕਾਊ ਖੇਤੀਬਾੜੀ AI',
      'loading': 'AI ਮਾਡਲ ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
      'version': 'v2.4.0 • ਸੁਰੱਖਿਅਤ ਨਿਊਰਲ ਕੋਰ',
      'welcome_back': 'ਵਾਪਸ ਸੁਆਗਤ ਹੈ,',
      'hello_farmer': 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ ਕਿਸਾਨ 🌱',
      'crops_healthy': 'ਤੁਹਾਡੀਆਂ ਫਸਲਾਂ ਅੱਜ ਸਿਹਤਮੰਦ ਦਿਖ ਰਹੀਆਂ ਹਨ।',
      'scan_leaf': 'ਪੱਤਾ ਸਕੈਨ ਕਰੋ',
      'scan_leaf_sub': 'ਤੁਰੰਤ ਬਿਮਾਰੀ ਖੋਜ ਅਤੇ ਸਲਾਹ',
      'local_conditions': 'ਸਥਾਨਕ ਹਾਲਾਤ',
      'temp': 'ਤਾਪਮਾਨ',
      'sky': 'ਅਸਮਾਨ',
      'humidity': 'ਨਮੀ',
      'cloudy': 'ਬੱਦਲਵਾਈ',
      'tips_today': 'ਅੱਜ ਦੇ ਸੁਝਾਅ',
      'tips_text': 'ਫੰਗਲ ਵਾਧੇ ਨੂੰ ਰੋਕਣ ਲਈ ਸਵੇਰੇ ਜਲਦੀ ਪੌਦਿਆਂ ਨੂੰ ਪਾਣੀ ਦਿਓ।',
      'common_diseases': 'ਆਮ ਬਿਮਾਰੀਆਂ',
      'tomato': 'ਟਮਾਟਰ',
      'potato': 'ਆਲੂ',
      'pepper': 'ਮਿਰਚ',
      'nav_home': 'ਹੋਮ',
      'nav_expert': 'ਮਾਹਰ',
      'nav_chat': 'ਚੈਟ',
      'nav_settings': 'ਸੈਟਿੰਗਾਂ',
      'expert_advisory': 'ਮਾਹਰ ਸਲਾਹ',
      'scanned_specimen': 'ਸਕੈਨ ਕੀਤਾ ਨਮੂਨਾ',
      'disease': 'ਬਿਮਾਰੀ',
      'confidence': 'ਵਿਸ਼ਵਾਸ',
      'treatment': 'ਇਲਾਜ ਸੁਝਾਅ',
      'listen_advisory': 'ਸਲਾਹ ਸੁਣੋ',
      'stop_advisory': 'ਰੋਕੋ',
      'speak_advisory': 'ਸਲਾਹ ਬੋਲੋ',
      'listening': 'ਸੁਣ ਰਿਹਾ ਹਾਂ…',
      'speak_hint': 'ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਬੋਲੋ।',
      'scan_another': 'ਦੂਜਾ ਪੱਤਾ ਸਕੈਨ ਕਰੋ',
      'chat_title': 'AI ਮਾਹਰ ਨਾਲ ਚੈਟ ਕਰੋ',
      'type_message': 'ਸੁਨੇਹਾ ਟਾਈਪ ਕਰੋ...',
      'hold_speak': 'ਬੋਲਣ ਲਈ ਮਾਈਕ ਟੈਪ ਕਰੋ',
      'tap_stop': 'ਰੋਕਣ ਲਈ ਮਾਈਕ ਟੈਪ ਕਰੋ',
      'listening_now': 'ਸੁਣ ਰਿਹਾ ਹਾਂ...',
      'agri_expert': 'ਖੇਤੀ ਮਾਹਰ',
      'you': 'ਤੁਸੀਂ',
      'today': 'ਅੱਜ',
      'settings': 'ਸੈਟਿੰਗਾਂ',
      'language': 'ਭਾਸ਼ਾ',
      'select_language': 'ਭਾਸ਼ਾ ਚੁਣੋ',
      'notifications': 'ਸੂਚਨਾਵਾਂ',
      'about': 'ਜਾਣਕਾਰੀ',
      'version_label': 'ਸੰਸਕਰਣ',
    },

    // ── ASSAMESE ──────────────────────────────────────────────
    AppLanguage.assamese: {
      'app_name': 'এগ্ৰি ভইচ',
      'app_tagline': 'টেকসই কৃষি AI',
      'loading': 'AI মডেল লোড হৈ আছে...',
      'version': 'v2.4.0 • সুৰক্ষিত নিউৰেল কোৰ',
      'welcome_back': 'আপোনাক পুনৰ স্বাগতম,',
      'hello_farmer': 'নমস্কাৰ কৃষক 🌱',
      'crops_healthy': 'আপোনাৰ শস্য আজি সুস্থ দেখাইছে।',
      'scan_leaf': 'পাত স্কেন কৰক',
      'scan_leaf_sub': 'তৎক্ষণাত ৰোগ চিনাক্তকৰণ আৰু পৰামৰ্শ',
      'local_conditions': 'স্থানীয় অৱস্থা',
      'temp': 'উষ্ণতা',
      'sky': 'আকাশ',
      'humidity': 'আৰ্দ্ৰতা',
      'cloudy': 'মেঘলা',
      'tips_today': 'আজিৰ টিপছ',
      'tips_text': 'ভেঁকুৰৰ বৃদ্ধি ৰোধ কৰিবলৈ ৰাতিপুৱা গছবোৰত পানী দিয়ক।',
      'common_diseases': 'সাধাৰণ ৰোগ',
      'tomato': 'টমেটো',
      'potato': 'আলু',
      'pepper': 'জলকীয়া',
      'nav_home': 'হোম',
      'nav_expert': 'বিশেষজ্ঞ',
      'nav_chat': 'চেট',
      'nav_settings': 'ছেটিংছ',
      'expert_advisory': 'বিশেষজ্ঞ পৰামৰ্শ',
      'scanned_specimen': 'স্কেন কৰা নমুনা',
      'disease': 'ৰোগ',
      'confidence': 'বিশ্বাস',
      'treatment': 'চিকিৎসা পৰামৰ্শ',
      'listen_advisory': 'পৰামৰ্শ শুনক',
      'stop_advisory': 'বন্ধ কৰক',
      'speak_advisory': 'পৰামৰ্শ কওক',
      'listening': 'শুনি আছে…',
      'speak_hint': 'আপোনাৰ ভাষাত কথা কওক।',
      'scan_another': 'আন এখন পাত স্কেন কৰক',
      'chat_title': 'AI বিশেষজ্ঞৰ সৈতে চেট কৰক',
      'type_message': 'বাৰ্তা টাইপ কৰক...',
      'hold_speak': 'কথা ক\'বলৈ মাইক টেপ কৰক',
      'tap_stop': 'বন্ধ কৰিবলৈ মাইক টেপ কৰক',
      'listening_now': 'শুনি আছে...',
      'agri_expert': 'কৃষি বিশেষজ্ঞ',
      'you': 'আপুনি',
      'today': 'আজি',
      'settings': 'ছেটিংছ',
      'language': 'ভাষা',
      'select_language': 'ভাষা বাছক',
      'notifications': 'জাননী',
      'about': 'বিষয়ে',
      'version_label': 'সংস্কৰণ',
    },

    // ── URDU ──────────────────────────────────────────────────
    AppLanguage.urdu: {
      'app_name': 'اگری وائس',
      'app_tagline': 'پائیدار زراعت AI',
      'loading': 'AI ماڈل لوڈ ہو رہا ہے...',
      'version': 'v2.4.0 • محفوظ نیورل کور',
      'welcome_back': 'واپس خوش آمدید,',
      'hello_farmer': 'السلام علیکم کسان 🌱',
      'crops_healthy': 'آپ کی فصلیں آج صحت مند نظر آ رہی ہیں۔',
      'scan_leaf': 'پتہ اسکین کریں',
      'scan_leaf_sub': 'فوری بیماری کی تشخیص اور مشورہ',
      'local_conditions': 'مقامی حالات',
      'temp': 'درجہ حرارت',
      'sky': 'آسمان',
      'humidity': 'نمی',
      'cloudy': 'بادل',
      'tips_today': 'آج کی تجاویز',
      'tips_text': 'فنگل بڑھوتری کو روکنے کے لیے صبح سویرے پودوں کو پانی دیں۔',
      'common_diseases': 'عام بیماریاں',
      'tomato': 'ٹماٹر',
      'potato': 'آلو',
      'pepper': 'مرچ',
      'nav_home': 'ہوم',
      'nav_expert': 'ماہر',
      'nav_chat': 'چیٹ',
      'nav_settings': 'ترتیبات',
      'expert_advisory': 'ماہر مشورہ',
      'scanned_specimen': 'اسکین شدہ نمونہ',
      'disease': 'بیماری',
      'confidence': 'اعتماد',
      'treatment': 'علاج کی سفارش',
      'listen_advisory': 'مشورہ سنیں',
      'stop_advisory': 'روکیں',
      'speak_advisory': 'مشورہ بولیں',
      'listening': 'سن رہا ہوں…',
      'speak_hint': 'اپنی زبان میں بولیں۔',
      'scan_another': 'دوسرا پتہ اسکین کریں',
      'chat_title': 'AI ماہر سے چیٹ کریں',
      'type_message': 'پیغام ٹائپ کریں...',
      'hold_speak': 'بولنے کے لیے مائیک ٹیپ کریں',
      'tap_stop': 'روکنے کے لیے مائیک ٹیپ کریں',
      'listening_now': 'سن رہا ہوں...',
      'agri_expert': 'زرعی ماہر',
      'you': 'آپ',
      'today': 'آج',
      'settings': 'ترتیبات',
      'language': 'زبان',
      'select_language': 'زبان منتخب کریں',
      'notifications': 'اطلاعات',
      'about': 'کے بارے میں',
      'version_label': 'ورژن',
    },

    // ── KONKANI ───────────────────────────────────────────────
    AppLanguage.konkani: {
      'app_name': 'अॅग्री व्हॉइस',
      'app_tagline': 'टिकाव शेतकाम AI',
      'loading': 'AI मॉडेल लोड जाता आसा...',
      'version': 'v2.4.0 • सुरक्षित न्युरल कोर',
      'welcome_back': 'परत येवकार,',
      'hello_farmer': 'नमस्कार शेतकर 🌱',
      'crops_healthy': 'तुमचीं पिकां आयज निरोगी दिसतात.',
      'scan_leaf': 'पान स्कॅन करात',
      'scan_leaf_sub': 'तत्काळ रोग सोद आनी सल्लो',
      'local_conditions': 'स्थानीय परिस्थिती',
      'temp': 'तापमान',
      'sky': 'आकाश',
      'humidity': 'दमटपण',
      'cloudy': 'ढगाळ',
      'tips_today': 'आयजचे सुचोवणे',
      'tips_text': 'बुरशीची वाड रोखपाक सकाळीं झाडांक उदक दियात.',
      'common_diseases': 'सामान्य रोग',
      'tomato': 'टमाटो',
      'potato': 'बटाटो',
      'pepper': 'मिरसांग',
      'nav_home': 'मुखेल',
      'nav_expert': 'तज्ञ',
      'nav_chat': 'चॅट',
      'nav_settings': 'सेटिंग्ज',
      'expert_advisory': 'तज्ञ सल्लो',
      'scanned_specimen': 'स्कॅन केल्लो नमुनो',
      'disease': 'रोग',
      'confidence': 'विश्वास',
      'treatment': 'उपचार शिफारस',
      'listen_advisory': 'सल्लो आयक',
      'stop_advisory': 'थांबात',
      'speak_advisory': 'सल्लो उलोयात',
      'listening': 'आयकता आसा…',
      'speak_hint': 'तुमच्या भाशेन उलोयात.',
      'scan_another': 'दुसरें पान स्कॅन करात',
      'chat_title': 'AI तज्ञाकडे चॅट करात',
      'type_message': 'निरोप टायप करात...',
      'hold_speak': 'उलोवपाक मायक टॅप करात',
      'tap_stop': 'थांबोवपाक मायक टॅप करात',
      'listening_now': 'आयकता आसा...',
      'agri_expert': 'शेतकाम तज्ञ',
      'you': 'तुमी',
      'today': 'आयज',
      'settings': 'सेटिंग्ज',
      'language': 'भाशा',
      'select_language': 'भाशा निवडात',
      'notifications': 'सुचोवणे',
      'about': 'माहिती',
      'version_label': 'आवृत्ती',
    },

    // ── MAITHILI ──────────────────────────────────────────────
    AppLanguage.maithili: {
      'app_name': 'अग्री वॉइस',
      'app_tagline': 'टिकाऊ कृषि AI',
      'loading': 'AI मॉडल लोड भ रहल अछि...',
      'version': 'v2.4.0 • सुरक्षित न्यूरल कोर',
      'welcome_back': 'वापस स्वागत,',
      'hello_farmer': 'प्रणाम किसान 🌱',
      'crops_healthy': 'अहाँक फसल आइ स्वस्थ देखाइत अछि।',
      'scan_leaf': 'पत्ती स्कैन करू',
      'scan_leaf_sub': 'तुरत रोग पहचान आ सलाह',
      'local_conditions': 'स्थानीय स्थिति',
      'temp': 'तापमान',
      'sky': 'आकाश',
      'humidity': 'नमी',
      'cloudy': 'बादर',
      'tips_today': 'आइक टिप्स',
      'tips_text': 'फफूंद वृद्धि रोकय लेल सबेरे पौधा सभकेँ पानि दियौ।',
      'common_diseases': 'सामान्य रोग',
      'tomato': 'टमाटर',
      'potato': 'आलू',
      'pepper': 'मिरचाइ',
      'nav_home': 'होम',
      'nav_expert': 'विशेषज्ञ',
      'nav_chat': 'चैट',
      'nav_settings': 'सेटिंग',
      'expert_advisory': 'विशेषज्ञ सलाह',
      'scanned_specimen': 'स्कैन नमूना',
      'disease': 'रोग',
      'confidence': 'विश्वास',
      'treatment': 'उपचार सुझाव',
      'listen_advisory': 'सलाह सुनू',
      'stop_advisory': 'रोकू',
      'speak_advisory': 'सलाह बाजू',
      'listening': 'सुनि रहल अछि…',
      'speak_hint': 'अपन भाषामे बाजू।',
      'scan_another': 'दोसर पत्ती स्कैन करू',
      'chat_title': 'AI विशेषज्ञसँ चैट करू',
      'type_message': 'संदेश टाइप करू...',
      'hold_speak': 'बाजय लेल माइक टैप करू',
      'tap_stop': 'रोकय लेल माइक टैप करू',
      'listening_now': 'सुनि रहल अछि...',
      'agri_expert': 'कृषि विशेषज्ञ',
      'you': 'अहाँ',
      'today': 'आइ',
      'settings': 'सेटिंग',
      'language': 'भाषा',
      'select_language': 'भाषा चुनू',
      'notifications': 'सूचना',
      'about': 'जानकारी',
      'version_label': 'संस्करण',
    },

    // ── SANTALI (using Latin as Ol Chiki may not render) ──────
    AppLanguage.santali: {
      'app_name': 'Agri Voice',
      'app_tagline': 'Sustainable Kheti AI',
      'loading': 'AI Model load hoy...',
      'version': 'v2.4.0 • Neural Core',
      'welcome_back': 'Punas istaqbal,',
      'hello_farmer': 'Johar Kissan 🌱',
      'crops_healthy': 'Apnar phal-phulay aj svosth dekhayche.',
      'scan_leaf': 'Patla Scan Kor',
      'scan_leaf_sub': 'Turant Rog Pehchan & Salaah',
      'local_conditions': 'Thao Ko Dasa',
      'temp': 'Garmi',
      'sky': 'Akash',
      'humidity': 'Nami',
      'cloudy': 'Badal',
      'tips_today': 'Aj Ko Tips',
      'tips_text': 'Gach men pani deo phabhor.',
      'common_diseases': 'Rog Ko',
      'tomato': 'Tomato',
      'potato': 'Alu',
      'pepper': 'Mirchi',
      'nav_home': 'Ghare',
      'nav_expert': 'Gyani',
      'nav_chat': 'Chat',
      'nav_settings': 'Setting',
      'expert_advisory': 'Gyani Salaah',
      'scanned_specimen': 'Scan Namuna',
      'disease': 'Rog',
      'confidence': 'Bharosa',
      'treatment': 'Ilaaj',
      'listen_advisory': 'Salaah Suno',
      'stop_advisory': 'Band Kor',
      'speak_advisory': 'Salaah Bolo',
      'listening': 'Suneta...',
      'speak_hint': 'Apnar bhasay bolo.',
      'scan_another': 'Dusro Patla Scan Kor',
      'chat_title': 'AI Gyani Chat',
      'type_message': 'Message likho...',
      'hold_speak': 'Mic tap kor bolpak',
      'tap_stop': 'Mic tap kor band korpak',
      'listening_now': 'Suneta...',
      'agri_expert': 'Kheti Gyani',
      'you': 'Apne',
      'today': 'Aj',
      'settings': 'Setting',
      'language': 'Bhasha',
      'select_language': 'Bhasha Chunau',
      'notifications': 'Suchana',
      'about': 'Baare Me',
      'version_label': 'Version',
    },

    // ── KASHMIRI ──────────────────────────────────────────────
    AppLanguage.kashmiri: {
      'app_name': 'اگری وائس',
      'app_tagline': 'پایدار زراعت AI',
      'loading': 'AI ماڈل لوڈ سیتھ چھُ...',
      'version': 'v2.4.0 • محفوظ نیورل کور',
      'welcome_back': 'واپس خوش آمدید,',
      'hello_farmer': 'آداب کِسان 🌱',
      'crops_healthy': 'آپنہ کھیت آج صحتمند چھِ۔',
      'scan_leaf': 'پتہ سکین کرو',
      'scan_leaf_sub': 'فوری بیماری تشخیص',
      'local_conditions': 'مقامی حالات',
      'temp': 'گرمی',
      'sky': 'آسمان',
      'humidity': 'نمی',
      'cloudy': 'بادل',
      'tips_today': 'آج کے نکات',
      'tips_text': 'ہر صبح پودوں کو پانی دو۔',
      'common_diseases': 'عام بیماریاں',
      'tomato': 'ٹماٹر',
      'potato': 'آلو',
      'pepper': 'مرچ',
      'nav_home': 'گھر',
      'nav_expert': 'ماہر',
      'nav_chat': 'چیٹ',
      'nav_settings': 'ترتیبات',
      'expert_advisory': 'ماہر مشورہ',
      'scanned_specimen': 'سکین نمونہ',
      'disease': 'بیماری',
      'confidence': 'اعتماد',
      'treatment': 'علاج',
      'listen_advisory': 'مشورہ سنو',
      'stop_advisory': 'بند کرو',
      'speak_advisory': 'مشورہ بولو',
      'listening': 'سن رہا ہوں…',
      'speak_hint': 'اپنی زبان میں بولو۔',
      'scan_another': 'دوسرا پتہ سکین کرو',
      'chat_title': 'AI ماہر سے بات کرو',
      'type_message': 'پیغام لکھو...',
      'hold_speak': 'بولنے کے لیے مائیک دبائیں',
      'tap_stop': 'روکنے کے لیے مائیک دبائیں',
      'listening_now': 'سن رہا ہوں...',
      'agri_expert': 'زرعی ماہر',
      'you': 'آپ',
      'today': 'آج',
      'settings': 'ترتیبات',
      'language': 'زبان',
      'select_language': 'زبان منتخب کریں',
      'notifications': 'اطلاعات',
      'about': 'بارے میں',
      'version_label': 'ورژن',
    },

    // ── NEPALI ────────────────────────────────────────────────
    AppLanguage.nepali: {
      'app_name': 'अग्री भ्वाइस',
      'app_tagline': 'दिगो कृषि AI',
      'loading': 'AI मोडेल लोड हुँदैछ...',
      'version': 'v2.4.0 • सुरक्षित न्यूरल कोर',
      'welcome_back': 'फिर्ता स्वागत छ,',
      'hello_farmer': 'नमस्ते किसान 🌱',
      'crops_healthy': 'तपाईंका बाली आज स्वस्थ देखिन्छन्।',
      'scan_leaf': 'पात स्क्यान गर्नुहोस्',
      'scan_leaf_sub': 'तुरुन्त रोग पहिचान र सल्लाह',
      'local_conditions': 'स्थानीय अवस्था',
      'temp': 'तापक्रम',
      'sky': 'आकाश',
      'humidity': 'आर्द्रता',
      'cloudy': 'बादल',
      'tips_today': 'आजका सुझावहरू',
      'tips_text': 'ढुसी वृद्धि रोक्न बिहानै बिरुवालाई पानी दिनुहोस्।',
      'common_diseases': 'सामान्य रोगहरू',
      'tomato': 'गोलभेडा',
      'potato': 'आलु',
      'pepper': 'खुर्सानी',
      'nav_home': 'गृह',
      'nav_expert': 'विशेषज्ञ',
      'nav_chat': 'च्याट',
      'nav_settings': 'सेटिङ',
      'expert_advisory': 'विशेषज्ञ सल्लाह',
      'scanned_specimen': 'स्क्यान गरिएको नमुना',
      'disease': 'रोग',
      'confidence': 'विश्वास',
      'treatment': 'उपचार सिफारिस',
      'listen_advisory': 'सल्लाह सुन्नुहोस्',
      'stop_advisory': 'रोक्नुहोस्',
      'speak_advisory': 'सल्लाह बोल्नुहोस्',
      'listening': 'सुन्दैछु…',
      'speak_hint': 'आफ्नो भाषामा बोल्नुहोस्।',
      'scan_another': 'अर्को पात स्क्यान गर्नुहोस्',
      'chat_title': 'AI विशेषज्ञसँग च्याट गर्नुहोस्',
      'type_message': 'सन्देश टाइप गर्नुहोस्...',
      'hold_speak': 'बोल्न माइक ट्याप गर्नुहोस्',
      'tap_stop': 'रोक्न माइक ट्याप गर्नुहोस्',
      'listening_now': 'सुन्दैछु...',
      'agri_expert': 'कृषि विशेषज्ञ',
      'you': 'तपाईं',
      'today': 'आज',
      'settings': 'सेटिङ',
      'language': 'भाषा',
      'select_language': 'भाषा छान्नुहोस्',
      'notifications': 'सूचनाहरू',
      'about': 'बारेमा',
      'version_label': 'संस्करण',
    },

    // ── SINDHI ────────────────────────────────────────────────
    AppLanguage.sindhi: {
      'app_name': 'اگري وائس',
      'app_tagline': 'پائيدار زراعت AI',
      'loading': 'AI ماڊل لوڊ ٿي رهيو آهي...',
      'version': 'v2.4.0 • محفوظ نيورل ڪور',
      'welcome_back': 'واپس خوش آمديد,',
      'hello_farmer': 'سلام ڪسان 🌱',
      'crops_healthy': 'توهان جون فصلون اڄ صحتمند نظر اچن ٿيون.',
      'scan_leaf': 'پن اسڪين ڪريو',
      'scan_leaf_sub': 'فوري بيماري سڃاڻپ ۽ صلاح',
      'local_conditions': 'مقامي حالتون',
      'temp': 'گرمي',
      'sky': 'آسمان',
      'humidity': 'نمي',
      'cloudy': 'بادل',
      'tips_today': 'اڄ جون صلاحون',
      'tips_text': 'سوير صبح ٻوٽن کي پاڻي ڏيو.',
      'common_diseases': 'عام بيماريون',
      'tomato': 'ٽماٽو',
      'potato': 'آلو',
      'pepper': 'مرچ',
      'nav_home': 'گهر',
      'nav_expert': 'ماهر',
      'nav_chat': 'چيٽ',
      'nav_settings': 'ترتيبون',
      'expert_advisory': 'ماهر صلاح',
      'scanned_specimen': 'اسڪين نمونو',
      'disease': 'بيماري',
      'confidence': 'اعتماد',
      'treatment': 'علاج',
      'listen_advisory': 'صلاح ٻڌو',
      'stop_advisory': 'بند ڪريو',
      'speak_advisory': 'صلاح ڳالهايو',
      'listening': 'ٻڌي رهيو آهيان…',
      'speak_hint': 'پنهنجي ٻولي ۾ ڳالهايو.',
      'scan_another': 'ٻيو پن اسڪين ڪريو',
      'chat_title': 'AI ماهر سان چيٽ ڪريو',
      'type_message': 'پيغام لکو...',
      'hold_speak': 'ڳالهائڻ لاءِ مائيڪ ٽيپ ڪريو',
      'tap_stop': 'بند ڪرڻ لاءِ مائيڪ ٽيپ ڪريو',
      'listening_now': 'ٻڌي رهيو آهيان...',
      'agri_expert': 'زراعتي ماهر',
      'you': 'توهان',
      'today': 'اڄ',
      'settings': 'ترتيبون',
      'language': 'ٻولي',
      'select_language': 'ٻولي چونڊيو',
      'notifications': 'اطلاع',
      'about': 'باري ۾',
      'version_label': 'ورزن',
    },

    // ── DOGRI ─────────────────────────────────────────────────
    AppLanguage.dogri: {
      'app_name': 'अग्री वॉइस',
      'app_tagline': 'टिकाऊ खेती AI',
      'loading': 'AI मॉडल लोड होंदा पेया...',
      'version': 'v2.4.0 • सुरक्षित न्यूरल कोर',
      'welcome_back': 'वापस जी आया,',
      'hello_farmer': 'नमस्कार किसान 🌱',
      'crops_healthy': 'तुंदी फसल अज्ज ठीक लगदी ऐ।',
      'scan_leaf': 'पत्ता स्कैन करो',
      'scan_leaf_sub': 'तुरत बमारी पछान ते सलाह',
      'local_conditions': 'थांए दी हालत',
      'temp': 'गर्मी',
      'sky': 'आसमान',
      'humidity': 'नमी',
      'cloudy': 'बद्दल',
      'tips_today': 'अज्ज दे सुझाव',
      'tips_text': 'सुबह बेरे बूटेयां गी पानी दियो।',
      'common_diseases': 'आम बमारियां',
      'tomato': 'टमाटर',
      'potato': 'आलू',
      'pepper': 'मिर्च',
      'nav_home': 'घर',
      'nav_expert': 'माहर',
      'nav_chat': 'चैट',
      'nav_settings': 'सेटिंग',
      'expert_advisory': 'माहर सलाह',
      'scanned_specimen': 'स्कैन नमूना',
      'disease': 'बमारी',
      'confidence': 'भरोसा',
      'treatment': 'इलाज',
      'listen_advisory': 'सलाह सुनो',
      'stop_advisory': 'रोको',
      'speak_advisory': 'सलाह बोलो',
      'listening': 'सुनदा पेया...',
      'speak_hint': 'अपनी भाशा च बोलो।',
      'scan_another': 'दूजा पत्ता स्कैन करो',
      'chat_title': 'AI माहर कोल चैट करो',
      'type_message': 'संदेश टाइप करो...',
      'hold_speak': 'बोलने लेई माइक टैप करो',
      'tap_stop': 'रोकने लेई माइक टैप करो',
      'listening_now': 'सुनदा पेया...',
      'agri_expert': 'खेती माहर',
      'you': 'तुस्सां',
      'today': 'अज्ज',
      'settings': 'सेटिंग',
      'language': 'भाशा',
      'select_language': 'भाशा चुनो',
      'notifications': 'सूचना',
      'about': 'बारे च',
      'version_label': 'संस्करण',
    },

    // ── BODO ──────────────────────────────────────────────────
    AppLanguage.bodo: {
      'app_name': 'Agri Voice',
      'app_tagline': 'Sustainable Farming AI',
      'loading': 'AI Model load dauwa...',
      'version': 'v2.4.0 • Neural Core',
      'welcome_back': 'Nangou nwng swgwng,',
      'hello_farmer': 'Namaskaar Kisaan 🌱',
      'crops_healthy': 'Nwng ni phal aj swnglai.',
      'scan_leaf': 'Pathar Scan Kor',
      'scan_leaf_sub': 'Rog pehchan & Salah',
      'local_conditions': 'Thao Ko Haal',
      'temp': 'Garmi',
      'sky': 'Akash',
      'humidity': 'Nami',
      'cloudy': 'Badal',
      'tips_today': 'Aj Ko Tips',
      'tips_text': 'Phool ko pani deo phabhor.',
      'common_diseases': 'Rog Ko',
      'tomato': 'Tomato',
      'potato': 'Aloo',
      'pepper': 'Mirchi',
      'nav_home': 'Home',
      'nav_expert': 'Expert',
      'nav_chat': 'Chat',
      'nav_settings': 'Setting',
      'expert_advisory': 'Expert Salah',
      'scanned_specimen': 'Scan Namuna',
      'disease': 'Rog',
      'confidence': 'Bharosa',
      'treatment': 'Ilaaj',
      'listen_advisory': 'Salah Suno',
      'stop_advisory': 'Band',
      'speak_advisory': 'Salah Bolo',
      'listening': 'Suneta...',
      'speak_hint': 'Apnar bhasay bolo.',
      'scan_another': 'Aaru Pathar Scan',
      'chat_title': 'AI Expert Chat',
      'type_message': 'Message likhaw...',
      'hold_speak': 'Mic tap kori bolpak',
      'tap_stop': 'Mic tap kori band',
      'listening_now': 'Suneta...',
      'agri_expert': 'Kheti Expert',
      'you': 'Nwng',
      'today': 'Aj',
      'settings': 'Setting',
      'language': 'Bhasha',
      'select_language': 'Bhasha Chunau',
      'notifications': 'Suchana',
      'about': 'Baare Me',
      'version_label': 'Version',
    },

    // ── MANIPURI ──────────────────────────────────────────────
    AppLanguage.manipuri: {
      'app_name': 'Agri Voice',
      'app_tagline': 'Sustainable Farming AI',
      'loading': 'AI Model load touri...',
      'version': 'v2.4.0 • Neural Core',
      'welcome_back': 'Nungshiba amukta,',
      'hello_farmer': 'Khurumjari Kisaan 🌱',
      'crops_healthy': 'Nang gi phal adomba ashiba.',
      'scan_leaf': 'Ishing Scan Tou',
      'scan_leaf_sub': 'Takat Nongthang Peikhre',
      'local_conditions': 'Lairik Thouram',
      'temp': 'Taret',
      'sky': 'Eekai',
      'humidity': 'Nungthil',
      'cloudy': 'Ningol',
      'tips_today': 'Adu gi Tips',
      'tips_text': 'Fanggal nungsirang touri taret yamlasi.',
      'common_diseases': 'Nongthang Ko',
      'tomato': 'Tomato',
      'potato': 'Alu',
      'pepper': 'Maroi',
      'nav_home': 'Home',
      'nav_expert': 'Expert',
      'nav_chat': 'Chat',
      'nav_settings': 'Setting',
      'expert_advisory': 'Expert Sana',
      'scanned_specimen': 'Scan Namuna',
      'disease': 'Nongthang',
      'confidence': 'Nungaiba',
      'treatment': 'Cheitaba',
      'listen_advisory': 'Sana Hangba',
      'stop_advisory': 'Thenba',
      'speak_advisory': 'Sana Chatpa',
      'listening': 'Hangba touri...',
      'speak_hint': 'Nang gi lon de chatpa.',
      'scan_another': 'Adomba Ishing Scan',
      'chat_title': 'AI Expert Chat',
      'type_message': 'Message Type Tou...',
      'hold_speak': 'Chatpagi Mic Tap Tou',
      'tap_stop': 'Thengi Mic Tap Tou',
      'listening_now': 'Hangba touri...',
      'agri_expert': 'Farming Expert',
      'you': 'Nang',
      'today': 'Adu',
      'settings': 'Setting',
      'language': 'Lon',
      'select_language': 'Lon Shingba',
      'notifications': 'Khangba',
      'about': 'Matamda',
      'version_label': 'Version',
    },
  };

  static String get(String key, AppLanguage lang) {
    return _strings[lang]?[key] ?? _strings[AppLanguage.english]?[key] ?? key;
  }

  static List<AppLanguage> get allLanguages => AppLanguage.values;

  static String ttsLocale(AppLanguage lang) => switch (lang) {
    AppLanguage.marathi => 'mr-IN',
    AppLanguage.hindi => 'hi-IN',
    AppLanguage.bengali => 'bn-IN',
    AppLanguage.punjabi => 'pa-IN',
    AppLanguage.gujarati => 'gu-IN',
    AppLanguage.telugu => 'te-IN',
    AppLanguage.kannada => 'kn-IN',
    AppLanguage.tamil => 'ta-IN',
    AppLanguage.malayalam => 'ml-IN',
    AppLanguage.odia => 'or-IN',
    AppLanguage.assamese => 'as-IN',
    AppLanguage.urdu => 'ur-IN',
    AppLanguage.nepali => 'ne-IN',
    _ => 'en-US',
  };
}

// ─────────────────────────────────────────────────────────────
//  LANGUAGE PROVIDER
// ─────────────────────────────────────────────────────────────

class LanguageProvider extends InheritedWidget {
  final AppLanguage currentLanguage;
  final void Function(AppLanguage) setLanguage;

  const LanguageProvider({
    super.key,
    required this.currentLanguage,
    required this.setLanguage,
    required super.child,
  });

  static LanguageProvider of(BuildContext context) {
    return context.dependOnInheritedWidgetOfExactType<LanguageProvider>()!;
  }

  String t(String key) => AppTranslations.get(key, currentLanguage);

  @override
  bool updateShouldNotify(LanguageProvider oldWidget) =>
      currentLanguage != oldWidget.currentLanguage;
}

// ─────────────────────────────────────────────────────────────
//  LANGUAGE ROOT
// ─────────────────────────────────────────────────────────────

class LanguageRoot extends StatefulWidget {
  final Widget Function(BuildContext, AppLanguage) builder;
  const LanguageRoot({super.key, required this.builder});

  @override
  State<LanguageRoot> createState() => _LanguageRootState();
}

class _LanguageRootState extends State<LanguageRoot> {
  AppLanguage _lang = AppLanguage.english;
  void _setLanguage(AppLanguage lang) => setState(() => _lang = lang);

  @override
  Widget build(BuildContext context) {
    return LanguageProvider(
      currentLanguage: _lang,
      setLanguage: _setLanguage,
      child: widget.builder(context, _lang),
    );
  }
}

// ─────────────────────────────────────────────────────────────
//  LANGUAGE PICKER SHEET
// ─────────────────────────────────────────────────────────────

class LanguagePickerSheet extends StatelessWidget {
  const LanguagePickerSheet({super.key});

  static void show(BuildContext context) {
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      builder: (_) => const LanguagePickerSheet(),
    );
  }

  @override
  Widget build(BuildContext context) {
    final provider = LanguageProvider.of(context);
    return DraggableScrollableSheet(
      initialChildSize: 0.6,
      maxChildSize: 0.9,
      minChildSize: 0.4,
      expand: false,
      builder: (_, controller) => SafeArea(
        child: Column(
          children: [
            Padding(
              padding: const EdgeInsets.fromLTRB(16, 16, 16, 8),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Center(
                    child: Container(
                      width: 40,
                      height: 4,
                      decoration: BoxDecoration(
                        color: Colors.grey.shade300,
                        borderRadius: BorderRadius.circular(2),
                      ),
                    ),
                  ),
                  const SizedBox(height: 16),
                  Text(
                    provider.t('select_language'),
                    style: const TextStyle(
                      fontSize: 18,
                      fontWeight: FontWeight.w700,
                      color: Color(0xFF0F172A),
                    ),
                  ),
                ],
              ),
            ),
            Expanded(
              child: ListView(
                controller: controller,
                children: AppTranslations.allLanguages.map((lang) {
                  final info = AppTranslations.languageInfo[lang]!;
                  final selected = provider.currentLanguage == lang;
                  return ListTile(
                    contentPadding: const EdgeInsets.symmetric(horizontal: 16),
                    leading: Text(
                      info.flag,
                      style: const TextStyle(fontSize: 28),
                    ),
                    title: Text(
                      info.nativeName,
                      style: TextStyle(
                        fontWeight: selected
                            ? FontWeight.w700
                            : FontWeight.w500,
                        color: selected
                            ? const Color(0xFF2F7F34)
                            : const Color(0xFF1E293B),
                      ),
                    ),
                    subtitle: Text(
                      info.name,
                      style: TextStyle(
                        color: Colors.grey.shade500,
                        fontSize: 12,
                      ),
                    ),
                    trailing: selected
                        ? const Icon(
                            Icons.check_circle_rounded,
                            color: Color(0xFF2F7F34),
                          )
                        : null,
                    onTap: () {
                      provider.setLanguage(lang);
                      Navigator.pop(context);
                    },
                  );
                }).toList(),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
